audit_header: false
title: MDMV Real Estate Video Blog with Danny Cheung
description: Our mission at The Gold Standard Group is to be your best resource for Maryland real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Gold Standard Group, your professional Maryland Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: The Gold Standard Group with eXp Realty
  title:
  license_number:
  about_markdown: |
    We live and breathe by these words… SERVICE – INTEGRITY – COMMITMENT! Whether you are new to the market, thinking of moving up, or an experienced investor, my team and I have the expertise, proven track record, and resources to help you buy or sell your next home. Enthusiasm, area knowledge, technology savvy and personal concern for my clients’ interests combine to make us an outstanding resource for your real estate transaction. We work extensively to help Buyers and Sellers meet their real estate goals. Our power team brings a wealth of business and financial expertise to the table but mostly we understand and appreciate the TRUE meaning of Client SERVICE!

    Awards & Designations - Washingtonian Magazine 2015, 2016, 2017, 2018 and 2019 Top Realtor Team.
  brand: 
  brokerage: 
  market: 
  address: 9211 Corporate Blvd., Suite 250 Rockville, MD 20850
  phone: 301-569-6921
  phone_type:
  phone2:
  phone2_type: 
  email: admin@TheGoldStandardGroup.com
  url: http://ViewMarylandHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.viewmarylandhouses.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.viewmarylandhouses.com/results-gallery/?photo=1&sort=importdate&status=A

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.viewmarylandhouses.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Home?"
    CTA_text2: "Search the entire MLS for your Maryland home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.viewmarylandhouses.com/results-gallery/?photo=1&sort=importdate&status=A

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/The-Gold-Standard-Group-160944322014/
  linkedin_url: https://www.linkedin.com/in/TheGoldStandardGroup
  youtube_url: https://www.youtube.com/channel/UCvaejIkfTGIWJvdLHqwWpWw?view_as=subscriber
  twitter_url:
  instagram_url: https://www.instagram.com/thegoldstandardgroup/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Maryland Real Estate Podcast with Danny Cheung'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Maryland Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Gold Standard Group - your professional Maryland Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Maryland, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Danny Cheung'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: DVM Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#846a45'
  theme_color: '#cd2033'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#846a45'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
